const en = {
  brandSubtitle: 'Client assessment',
  language: 'العربية',
  secure: 'Secure form',
  accessEyebrow: 'Your progress starts here',
  accessTitle: 'Open your assessment',
  accessText: 'Use the two private codes shared by your coach. No account or password is needed.',
  clientCode: 'Client code',
  formCode: 'Form code',
  clientCodeHint: 'For example: CL-1024',
  formCodeHint: 'For example: FORM-8X2Q',
  continue: 'Continue securely',
  checking: 'Checking codes…',
  selectionEyebrow: 'Available assessments',
  selectionTitle: 'Choose an assessment',
  selectionText: 'Your coach has made these forms available for you.',
  initial: 'Initial assessment',
  update: 'Progress update',
  start: 'Start form',
  noForms: 'There are no assessments available for these codes right now.',
  formEyebrow: 'CoachHub assessment',
  welcome: 'Welcome',
  progress: 'complete',
  required: 'Required',
  chooseOne: 'Choose one option',
  chooseMany: 'Choose all that apply',
  yes: 'Yes',
  no: 'No',
  upload: 'Choose image',
  uploading: 'Uploading securely…',
  replace: 'Replace file',
  submittedNotice: 'Your answers are sent together only when you submit.',
  submit: 'Submit assessment',
  submitting: 'Submitting…',
  successEyebrow: 'Assessment received',
  successTitle: 'Thank you — you are all set.',
  successText: 'Your answers were saved securely and are ready for your coach to review.',
  reference: 'Submission reference',
  another: 'Submit another assessment',
  differentCodes: 'Use different codes',
  privateNote: 'Your codes and answers stay within this secure assessment session.',
  codeRequired: 'Enter both codes to continue.',
  codeInvalid: 'We could not verify those codes. Check them and try again.',
  requiredError: 'Please complete every required question before submitting.',
  questions: 'questions',
  section: 'Section',
} as const;
export type AssessmentCopyKey = keyof typeof en;
const ar: Record<AssessmentCopyKey, string> = {
  brandSubtitle: 'تقييم العميل',
  language: 'English',
  secure: 'نموذج آمن',
  accessEyebrow: 'تقدمك يبدأ من هنا',
  accessTitle: 'افتح نموذج التقييم',
  accessText: 'استخدم الرمزين الخاصين اللذين أرسلهما مدربك. لا تحتاج إلى حساب أو كلمة مرور.',
  clientCode: 'رمز العميل',
  formCode: 'رمز النموذج',
  clientCodeHint: 'مثال: CL-1024',
  formCodeHint: 'مثال: FORM-8X2Q',
  continue: 'متابعة بأمان',
  checking: 'جارٍ التحقق…',
  selectionEyebrow: 'التقييمات المتاحة',
  selectionTitle: 'اختر تقييمًا',
  selectionText: 'أتاح لك مدربك النماذج التالية.',
  initial: 'التقييم الأولي',
  update: 'تحديث التقدم',
  start: 'ابدأ النموذج',
  noForms: 'لا توجد تقييمات متاحة لهذه الرموز حاليًا.',
  formEyebrow: 'تقييم CoachHub',
  welcome: 'مرحبًا',
  progress: 'مكتمل',
  required: 'مطلوب',
  chooseOne: 'اختر إجابة واحدة',
  chooseMany: 'اختر كل ما ينطبق',
  yes: 'نعم',
  no: 'لا',
  upload: 'اختر صورة',
  uploading: 'جارٍ الرفع بأمان…',
  replace: 'استبدال الملف',
  submittedNotice: 'تُرسل إجاباتك معًا فقط عند الضغط على الإرسال.',
  submit: 'إرسال التقييم',
  submitting: 'جارٍ الإرسال…',
  successEyebrow: 'تم استلام التقييم',
  successTitle: 'شكرًا لك — تم كل شيء.',
  successText: 'حُفظت إجاباتك بأمان وأصبحت جاهزة لمراجعة مدربك.',
  reference: 'مرجع الإرسال',
  another: 'إرسال تقييم آخر',
  differentCodes: 'استخدام رموز مختلفة',
  privateNote: 'تظل رموزك وإجاباتك داخل جلسة التقييم الآمنة هذه.',
  codeRequired: 'أدخل الرمزين للمتابعة.',
  codeInvalid: 'تعذر التحقق من الرمزين. راجعهما وحاول مرة أخرى.',
  requiredError: 'يرجى إكمال كل الأسئلة المطلوبة قبل الإرسال.',
  questions: 'أسئلة',
  section: 'القسم',
};
const copy = { en, ar } as const;
export function assessmentCopy(language: 'en' | 'ar', key: AssessmentCopyKey): string {
  return copy[language][key];
}
